/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.cadastroproduto.telas;

import com.mycompany.cadastroproduto.Carro;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author aluno.den
 */
public class cadastrarCarro extends javax.swing.JFrame {
    
    private ArrayList<Carro> listadeCarros = new ArrayList<>();
    
    /**
     * Creates new form cadastrarCarro
     */
    public cadastrarCarro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        numPortasTxt = new javax.swing.JTextField();
        Cadastrar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        marcaTxt = new javax.swing.JTextField();
        Listar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        modeloTxt = new javax.swing.JTextField();
        Editar = new javax.swing.JButton();
        Remover = new javax.swing.JButton();
        Remove = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        telaTx = new javax.swing.JTextArea();

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastrar Carro", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("Número de Portas:");

        numPortasTxt.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        Cadastrar.setBackground(new java.awt.Color(0, 153, 0));
        Cadastrar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Cadastrar.setForeground(new java.awt.Color(255, 255, 255));
        Cadastrar.setText("Cadastrar Carro");
        Cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Marca:");

        marcaTxt.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        Listar.setBackground(new java.awt.Color(0, 153, 153));
        Listar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Listar.setForeground(new java.awt.Color(255, 255, 255));
        Listar.setText("Listar");
        Listar.setToolTipText("");
        Listar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("Modelo:");

        modeloTxt.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        Editar.setBackground(new java.awt.Color(204, 204, 0));
        Editar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Editar.setForeground(new java.awt.Color(255, 255, 255));
        Editar.setText("Editar");
        Editar.setToolTipText("");
        Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarActionPerformed(evt);
            }
        });

        Remover.setBackground(new java.awt.Color(204, 0, 0));
        Remover.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Remover.setForeground(new java.awt.Color(255, 255, 255));
        Remover.setText("Limpar tela");
        Remover.setToolTipText("");
        Remover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoverActionPerformed(evt);
            }
        });

        Remove.setBackground(new java.awt.Color(204, 0, 0));
        Remove.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Remove.setForeground(new java.awt.Color(255, 255, 255));
        Remove.setText("Remover");
        Remove.setToolTipText("");
        Remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveActionPerformed(evt);
            }
        });

        telaTx.setColumns(20);
        telaTx.setRows(5);
        jScrollPane1.setViewportView(telaTx);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(Remove, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Remover, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(numPortasTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(marcaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Cadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Listar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(modeloTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Editar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(numPortasTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cadastrar))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Listar)
                    .addComponent(marcaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(modeloTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Editar))
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Remover)
                    .addComponent(Remove))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarActionPerformed
        try {
           int numPortas = Integer.parseInt(numPortasTxt.getText());
           String marca = marcaTxt.getText().trim();
           String modelo = modeloTxt.getText().trim();
           
           if (numPortas < 1 || numPortas > 4) {
               JOptionPane.showMessageDialog(null, "Digite o número de portas validos!");
               return;
           } 
           
           if (marca.isEmpty() || modelo.isEmpty()) {
               JOptionPane.showMessageDialog(null, "Os campos não podem ficar vazio");
               return;
           }
           
           Carro c = new Carro(numPortas, marca, modelo);
           
           if (listadeCarros.add(c)){
               JOptionPane.showMessageDialog(null, "Carro cadastrado com sucesso!");
           }
           
           numPortasTxt.setText("");
           marcaTxt.setText("");
           modeloTxt.setText("");
           
        } catch(NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Digite um número de portas validos");
            return;
        }
        
        
        
    }//GEN-LAST:event_CadastrarActionPerformed

    private void ListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListarActionPerformed
        numPortasTxt.setText("");
        marcaTxt.setText("");
        modeloTxt.setText("");
        
        if (listadeCarros.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Nenhum carro cadastrado");
            return;
        }
        
        for (Carro c : listadeCarros) {
            telaTx.append("\nMarca: " + c.getMarca() + "\nModelo: " + c.getModelo() + "\nQuantidade de Portas: " + c.getNumeroPorta() + "\n");
        }
       
    }//GEN-LAST:event_ListarActionPerformed

    private void EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarActionPerformed
        try {
            JOptionPane.showMessageDialog(null, "Para editar de forma correta, Digite o modelo antigo e depois você digitará o nome do novo modelo do carro");
            
            String marca = marcaTxt.getText().trim();
            String modelo = modeloTxt.getText().trim();
            int numPortas = Integer.parseInt(numPortasTxt.getText());
            boolean alterouCarro = false;

            if (marca.isEmpty() || modelo.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Os campos não podem estar vazio");
                return;
            }

            if (numPortas < 1 || numPortas > 4) {
                JOptionPane.showMessageDialog(null, "Digite o número de portas validos!");
                return;
            }


            for(Carro c : listadeCarros) {
                if(c.getModelo().equalsIgnoreCase(modelo)) {
                    String novoModelo = JOptionPane.showInputDialog(null, "Digite o novo modelo do carro: ", JOptionPane.QUESTION_MESSAGE);

                    if (novoModelo.isEmpty()) {
                        JOptionPane.showMessageDialog(null, "Digite um modelo valido");
                        return;
                    }

                    c.setModelo(novoModelo);
                    c.setMarca(marca);
                    c.setNumeroPorta(numPortas);
                    alterouCarro = true;
                    break;
                }
            }

            if (alterouCarro) {
                modeloTxt.setText("");
                marcaTxt.setText("");
                numPortasTxt.setText("");
                telaTx.setText("");
                JOptionPane.showMessageDialog(null, "Dados do carro alterado com sucesso!");
                telaTx.setText("");
            } else {
                JOptionPane.showMessageDialog(null, "Os dados não foram alterados!");
            }    
            
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Número de portas invalidos");
        }
        
        
    }//GEN-LAST:event_EditarActionPerformed

    private void RemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoverActionPerformed
        numPortasTxt.setText("");
        modeloTxt.setText("");
        marcaTxt.setText("");
        telaTx.setText("");
    }//GEN-LAST:event_RemoverActionPerformed

    private void RemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveActionPerformed
        String modelo = modeloTxt.getText().trim();
        boolean carroRemovido = false;
        
        for (int i = 0; i < listadeCarros.size(); i++ ){
            if(listadeCarros.get(i).getModelo().equalsIgnoreCase(modelo)){
                listadeCarros.remove(i);
                carroRemovido = true;
                break;
            }
        }
        
        modeloTxt.setText("");
        telaTx.setText("");
        if (carroRemovido) {
            JOptionPane.showMessageDialog(null, "Carro removido com sucesso!");
            
        } else {
            JOptionPane.showMessageDialog(null, "Carro não foi removido");
        }
        
    }//GEN-LAST:event_RemoveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cadastrarCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cadastrarCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cadastrarCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cadastrarCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cadastrarCarro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cadastrar;
    private javax.swing.JButton Editar;
    private javax.swing.JButton Listar;
    private javax.swing.JButton Remove;
    private javax.swing.JButton Remover;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField marcaTxt;
    private javax.swing.JTextField modeloTxt;
    private javax.swing.JTextField numPortasTxt;
    private javax.swing.JTextArea telaTx;
    // End of variables declaration//GEN-END:variables
}
