/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.cadastropessoas.views;

import com.mycompany.cadastropessoas.controller.PessoaController;
import com.mycompany.cadastropessoas.models.Pessoa;
import java.awt.PageAttributes;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Adriano Mateus
 */
public class CadastroPessoa extends javax.swing.JFrame {
    
    private PessoaController controller = new PessoaController();
    private DefaultTableModel tabelaModelo;
    private int idSelecionado = -1;
    private boolean modoAtualizado = false;
    
    private void atualizarTabela() {
        tabelaModelo.setRowCount(0);
        
        ArrayList<Pessoa> lista = controller.listar();
        
        for (Pessoa p : lista ) {
            tabelaModelo.addRow(new Object[]{p.getId(), p.getNome(), p.getIdade()});
        }
        
    }
    
    private void buscarDinamicamente() {
        String nomeBuscado = txtBuscar.getText().trim();
        
        tabelaModelo.setRowCount(0);
        ArrayList<Pessoa> lista = controller.buscarPorNome(nomeBuscado);
        
        for (Pessoa p : lista) {
            tabelaModelo.addRow(new Object[]{p.getId(), p.getNome(), p.getIdade()});
        }
        
    }
    
    /**
     * Creates new form CadastroPessoa
     */
    public CadastroPessoa() {
        initComponents();
        tabelaModelo = (DefaultTableModel) tbLista.getModel();
        atualizarTabela();
        
        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter(){
            public void keyReleased (java.awt.event.KeyEvent evt) {
                buscarDinamicamente();
            }
        });
        
        tbLista.getSelectionModel().addListSelectionListener(e -> {
            // Garante que so clique na tabale so uma vez
            if(!e.getValueIsAdjusting()) {
                int linhaSelecionada = tbLista.getSelectedRow();
                
                // Verifica se há uma linha selecionada
                if (linhaSelecionada != -1) {
                    // Pegando o id da pessoa onde clicou na tabela
                    idSelecionado = (int) tbLista.getValueAt(linhaSelecionada, 0);
                    
                    
                    txtNome.setText((String) tbLista.getValueAt(linhaSelecionada, 1));

                    txtIdade.setText(String.valueOf(tbLista.getValueAt(linhaSelecionada, 2)));
                    
                    modoAtualizado = true;
                    Cadastrar.setText("Atualizar");
                }
            }
        });
        
        this.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                if(!tbLista.getBounds().contains(evt.getPoint())) {
                    tbLista.clearSelection();
                    idSelecionado = -1;
                    modoAtualizado = false;
                    txtNome.setText("");
                    txtIdade.setText("");
                    Cadastrar.setText("Cadastrar");
                }
            }
        });
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtIdade = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        Cadastrar = new javax.swing.JButton();
        Remover = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbLista = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Nome:");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Idade:");

        txtNome.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        txtIdade.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Buscar:");

        txtBuscar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        Cadastrar.setBackground(new java.awt.Color(0, 204, 0));
        Cadastrar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Cadastrar.setForeground(new java.awt.Color(255, 255, 255));
        Cadastrar.setText("Cadastrar");
        Cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarActionPerformed(evt);
            }
        });

        Remover.setBackground(new java.awt.Color(204, 0, 0));
        Remover.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Remover.setForeground(new java.awt.Color(255, 255, 255));
        Remover.setText("Remover");
        Remover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoverActionPerformed(evt);
            }
        });

        tbLista.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tbLista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id", "Nome", "Idade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbLista);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNome)
                            .addComponent(txtIdade)
                            .addComponent(txtBuscar))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Remover, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(0, 11, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(8, 8, 8)
                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Remover, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoverActionPerformed
        int linhaSelecionada = tbLista.getSelectedRow();
        
        if (linhaSelecionada != -1) {
            int id = (int) tbLista.getValueAt(linhaSelecionada, 0);
            controller.remover(id);
            atualizarTabela();
            
            txtNome.setText("");
            txtIdade.setText("");
            
            JOptionPane.showMessageDialog(null, "Pessoa removida com sucesso");
        } else {
            JOptionPane.showMessageDialog(null, "Selecione uma pessoa para remover");
        }
        
    }//GEN-LAST:event_RemoverActionPerformed

    private void CadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarActionPerformed
        String nome = txtNome.getText().trim();
        int idade;
        
        try {
            idade = Integer.parseInt(txtIdade.getText().trim());
            
            if (!nome.isEmpty()) {
                if(!modoAtualizado) {
                    controller.cadastrar(nome, idade);
                    JOptionPane.showMessageDialog(null, "Cadastro realizado com sucesso!"); 
                } else {
                    controller.atualizar(idSelecionado, nome, idade);
                    JOptionPane.showMessageDialog(null, "Atualização realizada com sucesso");
                    Cadastrar.setText("cadastrar");
                    idSelecionado = -1;
                    modoAtualizado = false;
                }
                
                atualizarTabela();
                txtNome.setText("");
                txtIdade.setText("");
            } else {
                JOptionPane.showMessageDialog(null, "O nome não pode ficar vazio");
            }
            
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Idade deve ser um número inteiro");
        }
            
        
    }//GEN-LAST:event_CadastrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroPessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroPessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroPessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroPessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroPessoa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cadastrar;
    private javax.swing.JButton Remover;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbLista;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtIdade;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
